trigger:
- none
pool:
  vmImage: ubuntu-latest
pr: none
parameters:
  - name: vmname
    type: string
steps:
- checkout: self
- task: AzureCLI@2
  displayName: Close VM using az cli
  inputs:
    azureSubscription: 'GERALEXGR'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm create \
         --name ${{parameters.vmname}} \
         --resource-group mk-space-game-rg \
         --image canonical:0001-com-ubuntu-server-focal:20_04-lts:latest \
         --size Standard_DS2_v2 \
         --admin-username azureuser \
         --generate-ssh-keys
      sudo apt-get update   
      curl https://raw.githubusercontent.com/MicrosoftDocs/mslearn-tailspin-spacegame-web/main/.agent-tools/build-tools.sh > build-tools.sh
      cat build-tools.sh
    
      