trigger:
- none
pool:
  vmImage: ubuntu-latest
pr: none
parameters:
  - name: vmname
    type: string
steps:
- checkout: self
- task: AzureCLI@2
  displayName: Close VM using az cli
  inputs:
    azureSubscription: 'GERALEXGR'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $vmrequest = az vm list | ConvertFrom-Json | Where-Object {$_.Name -Match "${{parameters.vmname}}"}  
      az vm start --resource-group $vmrequest.resourcegroup --name $vmrequest.name